keycloak:
  realm: pa
  auth-server-url: http://keycloak-cio.okd.gpn.cloud.nexign.com/auth/
  principal-attribute: preferred_username
  ssl-required: external
  resource: pa
  public-client: true
  confidential-port: 0
  bearer-only: true
