keycloak:
  auth-server-url: http://keycloak-cio.okd.gpn.cloud.nexign.com/auth
  principal-attribute: preferred_username
  public-client: true
  realm: pa
  resource: pa
  token-store: cookie
  token-cookie-path: /
#  security-constraints:
#    - authRoles:
#        - USER
#        - SUDO
#      securityCollections:
#        - patterns:
#            - /api/*
